# Generated by Django 5.1.7 on 2025-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('REGISTRAR', 'Registrar'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=100),
        ),
    ]
