# Generated by Django 5.1.6 on 2025-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('missing_marks', 'Missing marks'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30),
        ),
    ]
