# Generated by Django 5.2 on 2025-04-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("resolved", "Resolved"),
                            ("updated", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.SlugField(
                        blank=True,
                        help_text="Short identifier for the department, e.g., 'cs' for Computer Science.",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("missing_marks", "Missing Marks"),
                            ("appeal", "Appeal"),
                            ("corrections", "Corrections"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("course_code", models.CharField(max_length=20)),
                ("resolution_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Supporting documents for this issue (e.g., transcript, exam paper)",
                        null=True,
                        upload_to="issue_attachments/",
                    ),
                ),
            ],
        ),
    ]
