# Generated by Django 5.1.6 on 2025-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDPapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("LECTURER", "Lecturer"),
                    ("ADMIN", "Administrator"),
                ],
                max_length=100,
            ),
        ),
    ]
