# Generated by Django 5.1.5 on 2025-03-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='student_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
