# Generated by Django 5.1.5 on 2025-03-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPapp', '0002_issue_student_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
