# Generated by Django 5.1.7 on 2025-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDPapp", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("LECTURER", "Lecturer"),
                    ("ACADEMIC_REGISTRAR", "Academic Registrar"),
                    ("ADMIN", "Administrator"),
                ],
                max_length=100,
            ),
        ),
    ]
