# Generated by Django 5.1.7 on 2025-04-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPapp', '0002_issue_resolution_details_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.SlugField(blank=True, help_text="Short identifier for the department, e.g., 'cs' for Computer Science.", max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Full name of the department.', max_length=100, unique=True),
        ),
    ]
