# Generated by Django 5.1.7 on 2025-03-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SDPapp", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="reported_by",
        ),
    ]
