# Generated by Django 5.1.7 on 2025-04-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPapp', '0003_department_code_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
    ]
