# Generated by Django 5.1.7 on 2025-03-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDPapp", "0004_remove_issue_reported_by"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="custom_users",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("LECTURER", "Lecturer"),
                    ("ACADEMIC_REGISTRAR", "Academic Registrar"),
                    ("ADMIN", "Administrator"),
                ],
                default="Student",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_users_with_permission",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.CharField(
                choices=[
                    ("missing_marks", "Missing Marks"),
                    ("appeal", "Appeal"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="Open",
                max_length=30,
            ),
        ),
    ]
